<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MailKit" Version="2.15.0" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0" />
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.0" />
		<PackageReference Include="WindowsAzure.Storage" Version="9.3.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Taller_Mecanico.Common\Taller_Mecanico.Common.csproj" />
	</ItemGroup>

</Project>